# Generated by Django 5.2.4 on 2025-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Введите название страны",
                        max_length=100,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        help_text="Введите инн организации",
                        max_length=15,
                        null=True,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Введите адрес организации",
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["country"],
            },
        ),
    ]
