# Generated by Django 4.2.2 on 2025-08-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "permissions": [
                    ("can_unpublish_product", "Право на публикацию товара"),
                    ("can_delete_product", "Право на удаление продукта"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("public", "Опубликовано"), ("unpublic", "Не опубликовано")],
                default="unpublic",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
