# Generated by Django 4.2.2 on 2025-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("public", "Опубликовано"), ("unpublic", "Не опубликовано")],
                default="public",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
